#! /usr/bin/env python3
#
import pysam
import csv
import argparse
import os.path
import sys

parser = argparse.ArgumentParser()
parser.add_argument("bam", help="Required. the FULL path to the 10x bam file generated by cellranger count")
# parser.add_argument("-prefix", help="Optional, the prefix of the output bam; barcode.bam by defaultm")

args = parser.parse_args()

if os.path.exists(args.bam):
    pass
else:
    print("bam not found")
    sys.exit(1)

fin = pysam.AlignmentFile(args.bam, "rb")

# print(dir(fin.header))

# print(fin.header.values())
## this might be the header
# for line in fin.text.split('\n'):
#     print(line)

# i = 0
for read in fin:
    tags = read.tags
    CB_list = [ x for x in tags if x[0] == "CB"]
    RG_list = [ x for x in tags if x[0] == 'RG']
    if CB_list:
        # if (i > 20): break
        cell_barcode = CB_list[0][1]
        # current_rg = RG_list[0][1]
        # print(cell_barcode)
        # print(current_rg)
        # print(type(read))
        print('RG:Z:cellranger_standard:0:1:cb:'+ cell_barcode)
        # print(read[0])
        # print(read[22])
    else:
        print('')
        # i += 1
