run_name: 'GSE121861_kumar_mouse'
base: '/scratch/imallona/repeats_sc'
run_tech: 'chromium'
chemistry: 'SC3Pv2'
demux: False
genome_short: 'mm10'
genome: 'GRCm38'
genome_url: 'ftp://ftp.ensembl.org/pub/release-99/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz'
genes_gtf_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M24/gencode.vM24.annotation.gtf.gz'
rep_gtf_url: 'mm10_rmsk.gtf.gz'
transcriptome_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M24/gencode.vM24.pc_transcripts.fa.gz'
cellranger_db_id: 'refdata-gex-mm10-2020-A'
cellranger_db_url: 'https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-mm10-2020-A.tar.gz'
dependencies:
  gtf_parsing: '/home/imallona/src/repeats_sc/04_snakemake/scripts/gtf_parser.R'
  gtf_making: '/home/imallona/src/repeats_sc/04_snakemake/scripts/gtf_maker.R'
  featurecounts_parsing: '/home/imallona/src/repeats_sc/04_snakemake/scripts/plot_featurecounts_profile.R'
  get_barcodes: "/home/imallona/src/repeats_sc/04_snakemake/scripts/get_cell_barcodes.py"
  split_by_barcode: "/home/imallona/src/repeats_sc/04_snakemake/scripts/split_by_cell_barcode_in_sorted_bam.py"
software:
  Rscript: '/usr/local/R/R-4.1.0/bin/Rscript'
  bowtie_build: '/home/imallona/soft/bowtie/bowtie-1.2.3/bowtie-build'
  bowtie: '/home/imallona/soft/bowtie/bowtie-1.2.3/bowtie'
  pigz: '/usr/bin/pigz'
  star: '/home/imallona/soft/star/STAR-2.7.3a/source/STAR'
  featurecounts: '/home/imallona/soft/subread/subread-2.0.0-source/bin/featureCounts'
  cellranger: '/home/imallona/soft/cellranger/cellranger-3.1.0/cellranger'
  fastqdump: '/home/imallona/soft/sra-toools/sratoolkit.2.10.4-ubuntu64/bin/fastq-dump'
  vdb_validate: '/home/imallona/soft/sra-toools/sratoolkit.2.10.4-ubuntu64/bin/vdb-validate'
  prefetch: '/home/imallona/soft/sra-toools/sratoolkit.2.10.4-ubuntu64/bin/prefetch'
  bedtools: '/home/imallona/soft/bedtools/bedtools-2.29.2/bin/bedtools'
  salmon: '/home/imallona/soft/salmon/salmon-1.5.1/bin/salmon'
  gtf2bed: '/home/imallona/soft/bedops/bin/gtf2bed'
params:
  nthreads: 30
  local_mem_gb: 100
  remove_chr_string_from_gtf: True