run_name: 'SRR10974769'
base: '/home/imallona/repeats_sc'
run_tech: 'chromium'
chemistry: 'SC3Pv2'
demux: False
genome_short: 'hg38'
genome: 'GRCh38'
genome_url: 'ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz'
genes_gtf_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_33/gencode.v33.primary_assembly.annotation.gtf.gz'
rep_gtf_url: 'hg38_rmsk.gtf.gz'

transcriptome_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_33/gencode.v33.pc_transcripts.fa.gz'
cellranger_db_id: 'refdata-cellranger-GRCh38-3.0.0'
cellranger_db_url: 'http://cf.10xgenomics.com/supp/cell-exp/refdata-cellranger-GRCh38-3.0.0.tar.gz'
dependencies:
  gtf_parsing: '~/src/repeats_sc/04_snakemake/gtf_parser.R'
  gtf_making: '~/src/repeats_sc/04_snakemake/gtf_maker.R'
  featurecounts_parsing: '~/src/repeats_sc/04_snakemake/plot_featurecounts_profile.R'
  get_barcodes: "~/src/repeats_sc/04_snakemake/scripts/get_cell_barcodes.py"
  split_by_barcode: "~/src/repeats_sc/04_snakemake/scripts/split_by_cell_barcode_in_sorted_bam.py"
software:
  Rscript: '/usr/local/R/R-4.0.5/bin/Rscript'
  bowtie_build: '/home/imallona/soft/bowtie/bowtie-1.2.3/bowtie-build'
  bowtie: '/home/imallona/soft/bowtie/bowtie-1.2.3/bowtie'
  pigz: '/usr/bin/pigz'
  star: '~/soft/star/STAR-2.7.3a/source/STAR'
  featurecounts: '~/soft/subread/subread-2.0.0-source/bin/featureCounts'
  cellranger: '~/soft/cellranger/cellranger-3.1.0/cellranger'
  fastqdump: '~/soft/sra-toools/sratoolkit.2.10.4-ubuntu64/bin/fastq-dump'
  vdb_validate: '~/soft/sra-toools/sratoolkit.2.10.4-ubuntu64/bin/vdb-validate'
  prefetch: '~/soft/sra-toools/sratoolkit.2.10.4-ubuntu64/bin/prefetch'
  bedtools: '~/soft/bedtools/bedtools-2.29.2/bin/bedtools'
  salmon: '~/soft/salmon/salmon-1.1.0_linux_x86_64/bin/salmon'
  gtf2bed: '~/soft/bedops/bin/gtf2bed'
params:
  nthreads: 30
  local_mem_gb: 100
  remove_chr_string_from_gtf: True