#! /usr/bin/env python3
#
import pysam
import csv
import argparse
import os.path
import sys

parser = argparse.ArgumentParser()
parser.add_argument("bam", help="Required. the FULL path to the 10x bam file generated by cellranger count")

args = parser.parse_args()

if os.path.exists(args.bam):
    pass
else:
    print("bam not found")
    sys.exit(1)

fin = pysam.AlignmentFile(args.bam, "rb")

for read in fin:
    tags = read.tags
    CB_list = [ x for x in tags if x[0] == "CB"]
    RG_list = [ x for x in tags if x[0] == 'RG']
    if CB_list:
        cell_barcode = CB_list[0][1]
        print('RG:Z:cellranger_standard:0:1:cb:'+ cell_barcode)
    else:
        print('')
